name: spotube
description: Open source Spotify client that doesn't require Premium nor uses Electron! Available for both desktop & mobile!

publish_to: "none"

version: 3.9.0+38

homepage: https://spotube.krtirtho.dev
repository: https://github.com/KRTirtho/spotube

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  app_links:
  args:
  async:
  audio_service:
  audio_service_mpris:
  audio_session:
  auto_size_text:
  bonsoir:
  buttons_tabbar:
  cached_network_image:
  collection:
  curved_navigation_bar:
  desktop_webview_window:
    git:
      path: packages/desktop_webview_window
      ref: feat/cookies
      url: https://github.com/KRTirtho/flutter-plugins.git
  device_info_plus:
  dio:
  disable_battery_optimization:
  draggable_scrollbar:
    git:
      ref: cfd570035bf393de541d32e9b28808b5d7e602df
      url: https://github.com/thielepaul/flutter-draggable-scrollbar.git
  drift:
  duration:
  encrypt:
  envied:
  file_picker:
  file_selector:
  fluentui_system_icons:
  flutter:
    sdk: flutter
  flutter_broadcasts:
  flutter_cache_manager:
  flutter_discord_rpc:
  flutter_displaymode:
  flutter_feather_icons:
  flutter_hooks:
  flutter_inappwebview:
  flutter_localizations:
    sdk: flutter
  flutter_native_splash:
  flutter_riverpod:
  flutter_secure_storage: ^9.0.0
  flutter_sharing_intent:
  flutter_svg:
  form_validator:
  freezed_annotation:
  fuzzywuzzy:
  gap:
  go_router:
  google_fonts:
  hive:
  hive_flutter:
  hooks_riverpod:
  html:
  html_unescape:
  http:
  image_picker:
  intl:
  invidious:
  jiosaavn:
  json_annotation:
  local_notifier:
  logger:
  lrc:
  media_kit:
  media_kit_libs_audio:
  metadata_god:
  mime:
  open_file:
  package_info_plus:
  palette_generator:
  path:
  path_provider:
  permission_handler:
  piped_client:
  popover:
  riverpod:
  scrobblenaut:
    git:
      ref: dart-3-support
      url: https://github.com/KRTirtho/scrobblenaut.git
  scroll_to_index:
  shared_preferences:
  shelf:
  shelf_router:
  shelf_web_socket:
  sidebarx:
  simple_icons:
  skeletonizer:
  sliver_tools:
  smtc_windows:
  spotify:
  sqlite3:
  sqlite3_flutter_libs:
  stroke_text:
  system_theme:
  test:
  timezone:
  titlebar_buttons:
  tray_manager:
  url_launcher:
  uuid:
  version:
  very_good_infinite_list:
  visibility_detector:
  web_socket_channel:
  wikipedia_api:
  win32_registry:
  window_manager:
  youtube_explode_dart:

dev_dependencies:
  build_runner:
  crypto:
  envied_generator:
  flutter_gen_runner:
  flutter_launcher_icons:
  flutter_lints:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  hive_generator:
  json_serializable:
  freezed:
  custom_lint:
  riverpod_lint:
  process_run:
  pubspec_parse:
  pub_api_client:
  xml:
  io:
  drift_dev:

dependency_overrides:
  web:
  meta:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/tutorial/
    - assets/logos/
    - LICENSE

flutter_gen:
  output: lib/collections

flutter_native_splash:
  background_image: assets/bengali-patterns-bg.jpg
  image: assets/spotube-logo.png
  branding: assets/branding.png
  android_12:
    image: assets/spotube-logo_android12.png
    branding: assets/branding.png
    color: "#000000"
    icon_background_color: "#000000"
